spring:
  task:
    scheduling:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  scheduler:
    enabled: false
  jwt:
    secret: ${JWT_SECRET:TEST_SECRET_64_CHARS_MIN_1234567890_TEST_SECRET_64_CHARS}
    expiration-minutes: ${JWT_EXP_MINUTES:60}
